name: Build, Test and Publish

on:
  push:
    branches: [canary, main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up GitHub User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@oeduardoal"

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  publishRelease:
    name: Potentially publish release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@oeduardoal"

      - name: Setup GitHub User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Release
        if: github.ref == 'refs/heads/main'
        run: yarn run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for github-release
