name: Build, Test and Publish

on:
  push:
    branches: [canary]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GitHub User
        run: |
          git config --global user.email oeduardoal@gmail.com
          git config --global user.name "Eduardo Almeida"

      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@oeduardoal"

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files

      # run build

      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  publishRelease:
    name: Potentially publish release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@oeduardoal"

      - name: Setup GitHub User
        run: |
          git config --global user.email oeduardoal@gmail.com
          git config --global user.name "Eduardo Almeida"

      - name: Publish
        run: ./scripts/publish-release.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
