name: Build, Test and Publish

on:
  push:
    branches:
      - ci
      - main
      - canary
  pull_request:
    branches:
      - ci
      - main
      - canary
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub Checkout
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo '$GITHUB_CONTEXT'

      - name: PR
        run: echo "PR"

      - name: Canary
        if: github.ref == 'refs/heads/canary'
        run: echo "Commit in canary"

      - name: Main
        if: github.ref == 'refs/heads/main'
        run: echo "Commit in main"
        