name: Build, Test and Publish

on:
  push:
    branches:
      - main
      - canary
  pull_request:
    branches:
      - main
      - canary
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Set up GitHub Checkout
        uses: actions/checkout@v2

      - name: Setup GitHub User
        run: |
          git config --global user.email oeduardoal@gmail.com
          git config --global user.name "Eduardo Almeida"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo '$GITHUB_CONTEXT'

      - name: Use Node.js 11.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@oeduardoal'

      - name: PR
        run: echo "PR"

      - name: Canary
        if: github.ref == 'refs/heads/canary'
        run: yarn canary

      - name: Main
        if: github.ref == 'refs/heads/main'
        run: yarn release
        